# steps:
#   - name: python
#     entrypoint: pip
#     args: ["install", "-r", "requirements.txt", "--user"]

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '.']

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA']

#   - name: google/cloud-sdk
#     args: ['gcloud', 'run', 'deploy', 'helloworld', '--image=us-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']

# artifacts:
#   objects:
#     location: gs://$_BUCKET_NAME/
#     paths:
#       - ${SHORT_SHA}_test_log.xml

# images:
#   - us-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'